[package]
name = 'nx'
version = '0.1.0'
edition = '2021'

[dependencies]
xxhash-rust = { version = '0.8.5', features = ['xxh3', 'xxh64'] }
napi = { version = '2.12.6', default-features = false, features = ['anyhow', 'napi4', 'tokio_rt'] }
napi-derive = '2.9.3'
ignore = '0.4'
crossbeam-channel = '0.5'

globset = "0.4.10"
ignore-files = "1.3.0"
watchexec = "2.3.0"
watchexec-filterer-ignore = "1.2.1"
watchexec-events = "1.0.0"
watchexec-signals = "1.0.0"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
anyhow = "1.0.71"
thiserror = "1.0.40"
itertools = "0.10.5"
rayon = "1.7.0"
hashbrown = {version = "0.14.0", features = ["rayon"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonc-parser = {version =  "0.21.1", features = ["serde"] }

colored = "2"

[lib]
crate-type = ['cdylib']

[build-dependencies]
napi-build = '2.0.1'

[dev-dependencies]
assert_fs = "1.0.10"
